<?php

namespace Database\Seeders;

use App\Services\NotificationTemplateService;
use Illuminate\Database\Seeder;

class NotificationTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $service = app(NotificationTemplateService::class);

        $templates = [
            [
                'event_key' => 'customer.registered',
                'name' => 'Customer Registered',
                'category' => 'customer',
                'subject' => 'Welcome to VESTRA, {{customer_name}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Welcome to VESTRA Detergents. Your account has been created successfully.</p>',
                'sms_body' => 'Welcome to VESTRA Detergents, {{customer_name}}.',
                'in_app_body' => 'Welcome to VESTRA Detergents. Your account has been created successfully.',
                'variables_json' => ['customer_name', 'email'],
            ],
            [
                'event_key' => 'order.created',
                'name' => 'Order Created',
                'category' => 'order',
                'subject' => 'Your VESTRA Order {{order_number}} has been placed',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your order <strong>{{order_number}}</strong> has been placed successfully. Total: UGX {{amount}}.</p>',
                'sms_body' => 'VESTRA: Order {{order_number}} placed. Total UGX {{amount}}.',
                'in_app_body' => 'Your order {{order_number}} has been placed successfully.',
                'variables_json' => ['customer_name', 'order_number', 'invoice_number', 'amount'],
            ],
            [
                'event_key' => 'order.paid',
                'name' => 'Order Paid',
                'category' => 'order',
                'subject' => 'Payment Received for Order {{order_number}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>We received your payment of UGX {{amount}} for order <strong>{{order_number}}</strong>.</p>',
                'sms_body' => 'VESTRA: Payment received for order {{order_number}}. UGX {{amount}}.',
                'in_app_body' => 'Payment received for order {{order_number}}.',
                'variables_json' => ['customer_name', 'order_number', 'invoice_number', 'amount'],
            ],
            [
                'event_key' => 'order.shipped',
                'name' => 'Order Shipped',
                'category' => 'order',
                'subject' => 'Order {{order_number}} has been shipped',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your order <strong>{{order_number}}</strong> has been shipped. Tracking: {{tracking_number}}.</p>',
                'sms_body' => 'VESTRA: Order {{order_number}} shipped. Tracking: {{tracking_number}}.',
                'in_app_body' => 'Your order {{order_number}} has been shipped.',
                'variables_json' => ['customer_name', 'order_number', 'tracking_number'],
            ],
            [
                'event_key' => 'order.delivered',
                'name' => 'Order Delivered',
                'category' => 'order',
                'subject' => 'Order {{order_number}} delivered',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your order <strong>{{order_number}}</strong> has been delivered.</p>',
                'sms_body' => 'VESTRA: Order {{order_number}} delivered.',
                'in_app_body' => 'Your order {{order_number}} has been delivered.',
                'variables_json' => ['customer_name', 'order_number'],
            ],
            [
                'event_key' => 'order.cancelled',
                'name' => 'Order Cancelled',
                'category' => 'order',
                'subject' => 'Order {{order_number}} cancelled',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your order <strong>{{order_number}}</strong> has been cancelled. Reason: {{reason}}.</p>',
                'sms_body' => 'VESTRA: Order {{order_number}} cancelled.',
                'in_app_body' => 'Your order {{order_number}} has been cancelled.',
                'variables_json' => ['customer_name', 'order_number', 'reason'],
            ],
            [
                'event_key' => 'quote_request.admin_notification',
                'name' => 'New Quote Request Received',
                'category' => 'sales',
                'subject' => 'New Quote Request {{reference_number}} from {{company_name}}',
                'email_body' => '<p>A new quotation request has been submitted.</p><p><strong>Reference:</strong> {{reference_number}}<br><strong>Customer:</strong> {{customer_name}}<br><strong>Company:</strong> {{company_name}}<br><strong>Email:</strong> {{email}}<br><strong>Phone:</strong> {{phone}}<br><strong>Products:</strong> {{product_summary}}</p>',
                'sms_body' => 'VESTRA: New quote request {{reference_number}} from {{company_name}}.',
                'in_app_body' => 'New quote request {{reference_number}} from {{company_name}}.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name', 'email', 'phone', 'product_summary'],
            ],
            [
                'event_key' => 'quote_request.customer_confirmation',
                'name' => 'Quote Request Confirmation',
                'category' => 'sales',
                'subject' => 'We received your quote request {{reference_number}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>We have received your quotation request <strong>{{reference_number}}</strong> for {{company_name}}. Our sales team will contact you within 24–48 business hours.</p>',
                'sms_body' => 'VESTRA: Quote request {{reference_number}} received. We will contact you soon.',
                'in_app_body' => 'Your quote request {{reference_number}} has been received.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name'],
            ],
            [
                'event_key' => 'quote_request.approved',
                'name' => 'Quote Request Approved',
                'category' => 'sales',
                'subject' => 'Your quote {{reference_number}} was approved',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation request <strong>{{reference_number}}</strong> for {{company_name}} has been approved.</p>',
                'sms_body' => 'VESTRA: Quote {{reference_number}} approved.',
                'in_app_body' => 'Your quote request {{reference_number}} has been approved.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name', 'previous_status', 'new_status'],
            ],
            [
                'event_key' => 'quote_request.declined',
                'name' => 'Quote Request Declined',
                'category' => 'sales',
                'subject' => 'Update on quote {{reference_number}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation request <strong>{{reference_number}}</strong> for {{company_name}} was declined. Our team can help with alternatives.</p>',
                'sms_body' => 'VESTRA: Quote {{reference_number}} declined. Contact sales for options.',
                'in_app_body' => 'Your quote request {{reference_number}} was declined.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name', 'previous_status', 'new_status'],
            ],
            [
                'event_key' => 'quote_request.status_changed',
                'name' => 'Quote Request Status Updated',
                'category' => 'sales',
                'subject' => 'Quote {{reference_number}} status updated',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation request <strong>{{reference_number}}</strong> is now <strong>{{new_status}}</strong> (was {{previous_status}}).</p>',
                'sms_body' => 'VESTRA: Quote {{reference_number}} is now {{new_status}}.',
                'in_app_body' => 'Quote {{reference_number}} status is now {{new_status}}.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name', 'previous_status', 'new_status'],
            ],
            [
                'event_key' => 'distributor.application_submitted',
                'name' => 'Distributor Application Submitted',
                'category' => 'distributor',
                'subject' => 'Distributor Application Received',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your distributor application for <strong>{{company_name}}</strong> has been received and is under review.</p>',
                'sms_body' => 'VESTRA: Distributor application for {{company_name}} received.',
                'in_app_body' => 'Your distributor application for {{company_name}} has been received.',
                'variables_json' => ['customer_name', 'company_name'],
            ],
            [
                'event_key' => 'distributor.application_admin_notification',
                'name' => 'New Distributor Application Received',
                'category' => 'distributor',
                'subject' => 'New Distributor Application {{reference_number}} from {{company_name}}',
                'email_body' => '<p>A new distributor application has been submitted.</p><p><strong>Reference:</strong> {{reference_number}}<br><strong>Contact Person:</strong> {{customer_name}}<br><strong>Company:</strong> {{company_name}}<br><strong>Email:</strong> {{email}}<br><strong>Phone:</strong> {{phone}}<br><strong>District:</strong> {{district}}<br><strong>Business Type:</strong> {{business_type}}</p>',
                'sms_body' => 'VESTRA: New distributor application {{reference_number}} from {{company_name}}.',
                'in_app_body' => 'New distributor application {{reference_number}} from {{company_name}}.',
                'variables_json' => ['reference_number', 'customer_name', 'company_name', 'email', 'phone', 'district', 'business_type'],
            ],
            [
                'event_key' => 'distributor.application_approved',
                'name' => 'Distributor Application Approved',
                'category' => 'distributor',
                'subject' => 'Distributor Application Approved',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your distributor application for <strong>{{company_name}}</strong> has been approved.</p>',
                'sms_body' => 'VESTRA: Distributor application for {{company_name}} approved.',
                'in_app_body' => 'Your distributor application for {{company_name}} has been approved.',
                'variables_json' => ['customer_name', 'company_name'],
            ],
            [
                'event_key' => 'distributor.application_rejected',
                'name' => 'Distributor Application Rejected',
                'category' => 'distributor',
                'subject' => 'Distributor Application Update',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your distributor application for <strong>{{company_name}}</strong> was not approved. Reason: {{reason}}.</p>',
                'sms_body' => 'VESTRA: Distributor application for {{company_name}} not approved.',
                'in_app_body' => 'Your distributor application for {{company_name}} was not approved.',
                'variables_json' => ['customer_name', 'company_name', 'reason'],
            ],
            [
                'event_key' => 'security.password_changed',
                'name' => 'Password Changed',
                'category' => 'security',
                'subject' => 'Your VESTRA password was changed',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your account password was changed. If this was not you, please contact support immediately.</p>',
                'sms_body' => 'VESTRA: Your password was changed.',
                'in_app_body' => 'Your password was changed.',
                'variables_json' => ['customer_name', 'email'],
            ],
            [
                'event_key' => 'security.password_reset_requested',
                'name' => 'Password Reset Requested',
                'category' => 'security',
                'subject' => 'Reset your VESTRA password',
                'email_body' => '<p>Hi {{customer_name}},</p><p>We received a request to reset the password for {{email}}.</p><p><a href="{{reset_url}}">Reset your password</a></p><p>If you did not request this, you can ignore this email.</p>',
                'sms_body' => 'VESTRA: Password reset requested for {{email}}.',
                'in_app_body' => 'Password reset requested for your account.',
                'variables_json' => ['customer_name', 'email', 'token', 'reset_url'],
            ],
            [
                'event_key' => 'customer.profile_updated',
                'name' => 'Profile Updated',
                'category' => 'customer',
                'subject' => 'Your VESTRA profile was updated',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your account profile was updated successfully.</p>',
                'sms_body' => 'VESTRA: Your profile was updated.',
                'in_app_body' => 'Your profile was updated.',
                'variables_json' => ['customer_name'],
            ],
            [
                'event_key' => 'credit.limit_updated',
                'name' => 'Credit Limit Updated',
                'category' => 'distributor',
                'subject' => 'Credit limit updated for {{company_name}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>The credit limit for <strong>{{company_name}}</strong> is now UGX {{credit_limit}}.</p><p>Reason: {{reason}}</p>',
                'sms_body' => 'VESTRA: Credit limit for {{company_name}} updated to UGX {{credit_limit}}.',
                'in_app_body' => 'Credit limit for {{company_name}} updated to UGX {{credit_limit}}.',
                'variables_json' => ['customer_name', 'company_name', 'credit_limit', 'reason'],
            ],
            [
                'event_key' => 'order.packed',
                'name' => 'Order Packed',
                'category' => 'order',
                'subject' => 'Order {{order_number}} is packed',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your order <strong>{{order_number}}</strong> has been packed and is ready for dispatch.</p>',
                'sms_body' => 'VESTRA: Order {{order_number}} packed.',
                'in_app_body' => 'Your order {{order_number}} has been packed.',
                'variables_json' => ['customer_name', 'order_number'],
            ],
            [
                'event_key' => 'invoice.generated',
                'name' => 'Invoice Generated',
                'category' => 'order',
                'subject' => 'Invoice {{invoice_number}} generated',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Invoice <strong>{{invoice_number}}</strong> has been generated. Amount: UGX {{amount}}.</p>',
                'sms_body' => 'VESTRA: Invoice {{invoice_number}} generated. UGX {{amount}}.',
                'in_app_body' => 'Invoice {{invoice_number}} generated.',
                'variables_json' => ['customer_name', 'invoice_number', 'amount'],
            ],
            [
                'event_key' => 'quotation.submitted',
                'name' => 'Quotation Submitted',
                'category' => 'distributor',
                'subject' => 'Quotation {{quotation_number}} submitted',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation <strong>{{quotation_number}}</strong> has been submitted.</p>',
                'sms_body' => 'VESTRA: Quotation {{quotation_number}} submitted.',
                'in_app_body' => 'Quotation {{quotation_number}} submitted.',
                'variables_json' => ['customer_name', 'quotation_number'],
            ],
            [
                'event_key' => 'quotation.approved',
                'name' => 'Quotation Approved',
                'category' => 'distributor',
                'subject' => 'Quotation {{quotation_number}} approved',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation <strong>{{quotation_number}}</strong> has been approved.</p>',
                'sms_body' => 'VESTRA: Quotation {{quotation_number}} approved.',
                'in_app_body' => 'Quotation {{quotation_number}} approved.',
                'variables_json' => ['customer_name', 'quotation_number'],
            ],
            [
                'event_key' => 'quotation.rejected',
                'name' => 'Quotation Rejected',
                'category' => 'distributor',
                'subject' => 'Quotation {{quotation_number}} update',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your quotation <strong>{{quotation_number}}</strong> was not approved. Reason: {{reason}}.</p>',
                'sms_body' => 'VESTRA: Quotation {{quotation_number}} not approved.',
                'in_app_body' => 'Quotation {{quotation_number}} was not approved.',
                'variables_json' => ['customer_name', 'quotation_number', 'reason'],
            ],
            [
                'event_key' => 'payment.uploaded',
                'name' => 'Payment Uploaded',
                'category' => 'distributor',
                'subject' => 'Payment {{reference}} uploaded',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Payment reference <strong>{{reference}}</strong> for UGX {{amount}} was uploaded and is pending verification.</p>',
                'sms_body' => 'VESTRA: Payment {{reference}} uploaded.',
                'in_app_body' => 'Payment {{reference}} uploaded for verification.',
                'variables_json' => ['customer_name', 'reference', 'amount'],
            ],
            [
                'event_key' => 'payment.verified',
                'name' => 'Payment Verified',
                'category' => 'distributor',
                'subject' => 'Payment {{reference}} verified',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Payment reference <strong>{{reference}}</strong> for UGX {{amount}} has been verified.</p>',
                'sms_body' => 'VESTRA: Payment {{reference}} verified.',
                'in_app_body' => 'Payment {{reference}} verified.',
                'variables_json' => ['customer_name', 'reference', 'amount'],
            ],
            [
                'event_key' => 'statement.generated',
                'name' => 'Statement Generated',
                'category' => 'distributor',
                'subject' => 'Statement for {{company_name}} — {{statement_period}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your account statement for <strong>{{company_name}}</strong> ({{statement_period}}) is available.</p>',
                'sms_body' => 'VESTRA: Statement ready for {{company_name}}.',
                'in_app_body' => 'Statement generated for {{statement_period}}.',
                'variables_json' => ['customer_name', 'company_name', 'statement_period'],
            ],
            [
                'event_key' => 'review.approved',
                'name' => 'Review Approved',
                'category' => 'customer',
                'subject' => 'Your review of {{product_name}} was approved',
                'email_body' => '<p>Hi {{customer_name}},</p><p>Your review <strong>{{review_title}}</strong> for {{product_name}} is now published.</p>',
                'sms_body' => 'VESTRA: Your review for {{product_name}} was approved.',
                'in_app_body' => 'Your review for {{product_name}} was approved.',
                'variables_json' => ['customer_name', 'product_name', 'review_title'],
            ],
            [
                'event_key' => 'review.replied',
                'name' => 'Review Reply',
                'category' => 'customer',
                'subject' => 'Reply to your review of {{product_name}}',
                'email_body' => '<p>Hi {{customer_name}},</p><p>VESTRA replied to your review <strong>{{review_title}}</strong> for {{product_name}}.</p>',
                'sms_body' => 'VESTRA: Reply to your review of {{product_name}}.',
                'in_app_body' => 'New reply to your review of {{product_name}}.',
                'variables_json' => ['customer_name', 'product_name', 'review_title'],
            ],
            [
                'event_key' => 'product.price_dropped',
                'name' => 'Price Drop Alert',
                'category' => 'promotions',
                'subject' => 'Price drop on {{product_name}}',
                'email_body' => '<p>{{product_name}} is now UGX {{new_price}} (was UGX {{old_price}}).</p>',
                'sms_body' => 'VESTRA: {{product_name}} now UGX {{new_price}}.',
                'in_app_body' => 'Price drop on {{product_name}}.',
                'variables_json' => ['product_name', 'old_price', 'new_price'],
            ],
            [
                'event_key' => 'product.back_in_stock',
                'name' => 'Back In Stock',
                'category' => 'order',
                'subject' => '{{product_name}} is back in stock',
                'email_body' => '<p><a href="{{product_url}}">{{product_name}}</a> is back in stock.</p>',
                'sms_body' => 'VESTRA: {{product_name}} is back in stock.',
                'in_app_body' => '{{product_name}} is back in stock.',
                'variables_json' => ['product_name', 'product_url'],
            ],
            [
                'event_key' => 'admin.announcement',
                'name' => 'Admin Announcement',
                'category' => 'announcement',
                'subject' => '{{announcement_title}}',
                'email_body' => '<p>{{announcement_body}}</p>',
                'sms_body' => 'VESTRA: {{announcement_title}}',
                'in_app_body' => '{{announcement_body}}',
                'variables_json' => ['announcement_title', 'announcement_body', 'audience'],
            ],
            [
                'event_key' => 'system.maintenance_scheduled',
                'name' => 'System Maintenance Scheduled',
                'category' => 'system',
                'subject' => 'Scheduled Maintenance: {{window}}',
                'email_body' => '<p>Scheduled maintenance window: <strong>{{window}}</strong>.</p><p>{{description}}</p>',
                'sms_body' => 'VESTRA: Scheduled maintenance {{window}}.',
                'in_app_body' => 'Scheduled maintenance window: {{window}}.',
                'variables_json' => ['window', 'description'],
            ],
        ];

        foreach ($templates as $template) {
            $service->upsert($template);
        }
    }
}
