<?php

namespace Database\Seeders;

use App\Enums\SettingGroup;
use App\Enums\SettingType;
use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // General
            [
                'key' => 'app_name',
                'value' => 'VESTRA Admin',
                'type' => SettingType::STRING,
                'group' => SettingGroup::GENERAL,
                'label' => 'Application Name',
                'description' => 'Name shown in the administration panel and browser title.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'company_name',
                'value' => 'VESTRA',
                'type' => SettingType::STRING,
                'group' => SettingGroup::GENERAL,
                'label' => 'Company Name',
                'description' => 'Legal or trading name of the business.',
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'support_email',
                'value' => 'support@vestra.com',
                'type' => SettingType::STRING,
                'group' => SettingGroup::GENERAL,
                'label' => 'Support Email',
                'description' => 'Primary customer support email address.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'support_phone',
                'value' => '+1 (800) 555-0199',
                'type' => SettingType::STRING,
                'group' => SettingGroup::GENERAL,
                'label' => 'Support Phone',
                'description' => 'Primary customer support phone number.',
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'website_url',
                'value' => 'https://vestra.com',
                'type' => SettingType::STRING,
                'group' => SettingGroup::GENERAL,
                'label' => 'Website',
                'description' => 'Public website URL.',
                'sort_order' => 5,
                'is_public' => true,
            ],
            [
                'key' => 'company_logo',
                'value' => null,
                'type' => SettingType::IMAGE,
                'group' => SettingGroup::GENERAL,
                'label' => 'Company Logo',
                'description' => 'Logo used in admin panel and public branding.',
                'sort_order' => 6,
                'is_public' => true,
            ],
            [
                'key' => 'favicon',
                'value' => null,
                'type' => SettingType::IMAGE,
                'group' => SettingGroup::GENERAL,
                'label' => 'Favicon',
                'description' => 'Browser tab icon.',
                'sort_order' => 7,
                'is_public' => true,
            ],
            [
                'key' => 'business_address',
                'value' => '123 Fabric Lane, New York, NY 10001',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Business Address',
                'description' => 'Primary business address displayed to customers.',
                'sort_order' => 8,
                'is_public' => true,
            ],
            [
                'key' => 'timezone',
                'value' => 'Africa/Kampala',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Timezone',
                'description' => 'Default timezone for dates and times.',
                'options' => [
                    'Africa/Kampala' => 'Kampala',
                    'UTC' => 'UTC',
                    'America/New_York' => 'New York',
                    'Europe/London' => 'London',
                    'Asia/Dubai' => 'Dubai',
                ],
                'sort_order' => 9,
                'is_public' => true,
            ],
            [
                'key' => 'language',
                'value' => 'en',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Language',
                'description' => 'Default application language.',
                'options' => ['en' => 'English', 'fr' => 'French', 'es' => 'Spanish', 'sw' => 'Swahili'],
                'sort_order' => 10,
                'is_public' => true,
            ],
            [
                'key' => 'date_format',
                'value' => 'd M Y',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Date Format',
                'description' => 'Format used when displaying dates.',
                'options' => ['d M Y' => '01 Jan 2024', 'Y-m-d' => '2024-01-01', 'm/d/Y' => '01/01/2024', 'd/m/Y' => '01/01/2024'],
                'sort_order' => 11,
                'is_public' => true,
            ],
            [
                'key' => 'currency',
                'value' => 'UGX',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::GENERAL,
                'label' => 'Currency',
                'description' => 'Default currency code for pricing.',
                'options' => ['UGX' => 'Ugandan Shilling (UGX)', 'USD' => 'US Dollar (USD)', 'EUR' => 'Euro (EUR)', 'GBP' => 'British Pound (GBP)'],
                'sort_order' => 12,
                'is_public' => true,
            ],

            // Business
            [
                'key' => 'business_registration',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Business Registration',
                'description' => 'Official business registration number.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'tax_number',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Tax Number',
                'description' => 'Tax identification number.',
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'vat_number',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::BUSINESS,
                'label' => 'VAT Number',
                'description' => 'Value-added tax registration number.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'invoice_prefix',
                'value' => 'INV-',
                'type' => SettingType::STRING,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Invoice Prefix',
                'description' => 'Prefix used on invoice numbers.',
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'invoice_starting_number',
                'value' => '1000',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Invoice Starting Number',
                'description' => 'Starting number for invoice sequences.',
                'sort_order' => 5,
                'is_public' => true,
            ],
            [
                'key' => 'default_distributor_status',
                'value' => 'pending',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Default Distributor Status',
                'description' => 'Default status assigned to new distributor applications.',
                'options' => ['pending' => 'Pending', 'under_review' => 'Under Review'],
                'sort_order' => 6,
                'is_public' => true,
            ],
            [
                'key' => 'business_hours',
                'value' => 'Mon - Fri: 8:00 AM - 6:00 PM',
                'type' => SettingType::STRING,
                'group' => SettingGroup::BUSINESS,
                'label' => 'Business Hours',
                'description' => 'Publicly displayed business hours.',
                'sort_order' => 7,
                'is_public' => true,
            ],

            // Commerce
            [
                'key' => 'default_product_status',
                'value' => 'active',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Default Product Status',
                'description' => 'Default status for newly created products.',
                'options' => ['active' => 'Active', 'inactive' => 'Inactive'],
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'default_review_behaviour',
                'value' => 'manual',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Default Review Behaviour',
                'description' => 'How customer reviews are handled by default.',
                'options' => ['manual' => 'Manual moderation', 'auto' => 'Auto-approve'],
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'featured_product_rules',
                'value' => 'Staff selected',
                'type' => SettingType::STRING,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Featured Product Rules',
                'description' => 'Rules for selecting featured products.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'stock_threshold',
                'value' => '10',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Stock Threshold',
                'description' => 'Quantity at which products are considered low stock.',
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'default_category',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Default Category',
                'description' => 'Default category slug for new products.',
                'sort_order' => 5,
                'is_public' => true,
            ],
            [
                'key' => 'price_precision',
                'value' => '2',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Price Precision',
                'description' => 'Number of decimal places for prices.',
                'sort_order' => 6,
                'is_public' => true,
            ],
            [
                'key' => 'tax_display',
                'value' => 'exclusive',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::COMMERCE,
                'label' => 'Tax Display',
                'description' => 'Whether prices include or exclude tax.',
                'options' => ['exclusive' => 'Exclusive of tax', 'inclusive' => 'Inclusive of tax'],
                'sort_order' => 7,
                'is_public' => true,
            ],

            // Orders
            [
                'key' => 'order_number_prefix',
                'value' => 'ORD-',
                'type' => SettingType::STRING,
                'group' => SettingGroup::ORDERS,
                'label' => 'Order Number Prefix',
                'description' => 'Prefix for generated order numbers.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'default_order_status',
                'value' => 'pending',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::ORDERS,
                'label' => 'Default Order Status',
                'description' => 'Status assigned to new orders.',
                'options' => ['pending' => 'Pending', 'processing' => 'Processing'],
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'cancellation_window_hours',
                'value' => '24',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::ORDERS,
                'label' => 'Cancellation Window',
                'description' => 'Hours after order creation within which customers may cancel.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'auto_archive_days',
                'value' => '90',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::ORDERS,
                'label' => 'Auto Archive Days',
                'description' => 'Days after delivery before orders are archived. Set to 0 to disable.',
                'sort_order' => 4,
                'is_public' => true,
            ],

            // Payments
            [
                'key' => 'enabled_payment_methods',
                'value' => json_encode(['flutterwave', 'cod']),
                'type' => SettingType::JSON,
                'group' => SettingGroup::PAYMENTS,
                'label' => 'Enabled Payment Methods',
                'description' => 'JSON array of enabled payment method identifiers.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'default_payment_method',
                'value' => 'flutterwave',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::PAYMENTS,
                'label' => 'Default Payment Method',
                'description' => 'Default payment method at checkout.',
                'options' => ['flutterwave' => 'Flutterwave', 'cod' => 'Cash on Delivery', 'bank_transfer' => 'Bank Transfer'],
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'offline_payment_instructions',
                'value' => 'Please make payment to the bank account provided in your invoice.',
                'type' => SettingType::TEXT,
                'group' => SettingGroup::PAYMENTS,
                'label' => 'Offline Payment Instructions',
                'description' => 'Instructions shown when offline payment is selected.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'payment_timeout_minutes',
                'value' => '30',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::PAYMENTS,
                'label' => 'Payment Timeout',
                'description' => 'Minutes before an unpaid order is considered expired.',
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'transaction_reference_prefix',
                'value' => 'TXN-',
                'type' => SettingType::STRING,
                'group' => SettingGroup::PAYMENTS,
                'label' => 'Transaction Reference Prefix',
                'description' => 'Prefix for payment transaction references.',
                'sort_order' => 5,
                'is_public' => true,
            ],

            // Inventory
            [
                'key' => 'low_stock_threshold',
                'value' => '10',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::INVENTORY,
                'label' => 'Low Stock Threshold',
                'description' => 'Stock level that triggers low-stock alerts.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'out_of_stock_behaviour',
                'value' => 'hide',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::INVENTORY,
                'label' => 'Out of Stock Behaviour',
                'description' => 'How out-of-stock products are handled on the storefront.',
                'options' => ['hide' => 'Hide from storefront', 'show' => 'Show but disable purchase', 'notify' => 'Show with notify-me option'],
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'inventory_alerts_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::INVENTORY,
                'label' => 'Inventory Alerts',
                'description' => 'Enable low-stock and out-of-stock alerts.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'sku_format',
                'value' => 'VESTRA-{CATEGORY}-{SEQUENCE}',
                'type' => SettingType::STRING,
                'group' => SettingGroup::INVENTORY,
                'label' => 'SKU Format',
                'description' => 'Pattern used when generating SKUs.',
                'sort_order' => 4,
                'is_public' => true,
            ],

            // Notifications
            [
                'key' => 'admin_notifications_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Admin Notifications',
                'description' => 'Enable notifications to administrators.',
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'customer_notifications_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Customer Notifications',
                'description' => 'Enable notifications to customers.',
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'distributor_notifications_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Distributor Notifications',
                'description' => 'Enable notifications to distributors.',
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'review_notifications_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Review Notifications',
                'description' => 'Notify administrators of new reviews.',
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'email_notifications_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::NOTIFICATIONS,
                'label' => 'Email Notifications',
                'description' => 'Send notifications via email.',
                'sort_order' => 5,
                'is_public' => true,
            ],

            // Email
            [
                'key' => 'smtp_host',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::EMAIL,
                'label' => 'SMTP Host',
                'description' => 'Outgoing mail server hostname.',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'smtp_port',
                'value' => '587',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::EMAIL,
                'label' => 'SMTP Port',
                'description' => 'Outgoing mail server port.',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'smtp_encryption',
                'value' => 'tls',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::EMAIL,
                'label' => 'Encryption',
                'description' => 'Connection encryption method.',
                'options' => ['tls' => 'TLS', 'ssl' => 'SSL', 'none' => 'None'],
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'smtp_username',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::EMAIL,
                'label' => 'Username',
                'description' => 'SMTP authentication username.',
                'sort_order' => 4,
                'is_public' => false,
            ],
            [
                'key' => 'smtp_password',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::EMAIL,
                'label' => 'Password',
                'description' => 'SMTP authentication password.',
                'sort_order' => 5,
                'is_public' => false,
            ],
            [
                'key' => 'sender_name',
                'value' => 'VESTRA',
                'type' => SettingType::STRING,
                'group' => SettingGroup::EMAIL,
                'label' => 'Sender Name',
                'description' => 'Name displayed in the From field.',
                'sort_order' => 6,
                'is_public' => false,
            ],
            [
                'key' => 'sender_email',
                'value' => 'noreply@vestra.com',
                'type' => SettingType::STRING,
                'group' => SettingGroup::EMAIL,
                'label' => 'Sender Email',
                'description' => 'Email address used in the From field.',
                'sort_order' => 7,
                'is_public' => false,
            ],

            // Localization
            [
                'key' => 'default_language',
                'value' => 'en',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Language',
                'description' => 'Default storefront and admin language.',
                'options' => ['en' => 'English', 'fr' => 'French', 'es' => 'Spanish', 'sw' => 'Swahili'],
                'sort_order' => 1,
                'is_public' => true,
            ],
            [
                'key' => 'localization_timezone',
                'value' => 'Africa/Kampala',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Timezone',
                'description' => 'Default application timezone.',
                'options' => [
                    'Africa/Kampala' => 'Kampala',
                    'UTC' => 'UTC',
                    'America/New_York' => 'New York',
                    'Europe/London' => 'London',
                    'Asia/Dubai' => 'Dubai',
                ],
                'sort_order' => 2,
                'is_public' => true,
            ],
            [
                'key' => 'localization_date_format',
                'value' => 'd M Y',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Date Format',
                'description' => 'Format for displayed dates.',
                'options' => ['d M Y' => '01 Jan 2024', 'Y-m-d' => '2024-01-01', 'm/d/Y' => '01/01/2024', 'd/m/Y' => '01/01/2024'],
                'sort_order' => 3,
                'is_public' => true,
            ],
            [
                'key' => 'time_format',
                'value' => '12',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Time Format',
                'description' => '12-hour or 24-hour clock.',
                'options' => ['12' => '12-hour', '24' => '24-hour'],
                'sort_order' => 4,
                'is_public' => true,
            ],
            [
                'key' => 'number_format',
                'value' => 'en',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Number Format',
                'description' => 'Locale used for number formatting.',
                'options' => ['en' => '1,234.56', 'de' => '1.234,56', 'fr' => '1 234,56'],
                'sort_order' => 5,
                'is_public' => true,
            ],
            [
                'key' => 'currency_symbol',
                'value' => 'UGX',
                'type' => SettingType::STRING,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Currency Symbol',
                'description' => 'Symbol or code shown before or after amounts.',
                'sort_order' => 6,
                'is_public' => true,
            ],
            [
                'key' => 'currency_position',
                'value' => 'before',
                'type' => SettingType::SELECT,
                'group' => SettingGroup::LOCALIZATION,
                'label' => 'Currency Position',
                'description' => 'Display currency symbol before or after amount.',
                'options' => ['before' => 'Before amount', 'after' => 'After amount'],
                'sort_order' => 7,
                'is_public' => true,
            ],

            // Security
            [
                'key' => 'password_min_length',
                'value' => '12',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::SECURITY,
                'label' => 'Minimum Password Length',
                'description' => 'Minimum number of characters for passwords.',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'password_requires_symbols',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SECURITY,
                'label' => 'Require Symbols',
                'description' => 'Require special characters in passwords.',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'max_login_attempts',
                'value' => '5',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::SECURITY,
                'label' => 'Max Login Attempts',
                'description' => 'Failed attempts before temporary lockout.',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'session_timeout_minutes',
                'value' => '60',
                'type' => SettingType::NUMBER,
                'group' => SettingGroup::SECURITY,
                'label' => 'Session Timeout',
                'description' => 'Minutes of inactivity before automatic logout.',
                'sort_order' => 4,
                'is_public' => false,
            ],

            // Integrations
            [
                'key' => 'flutterwave_enabled',
                'value' => '1',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::INTEGRATIONS,
                'label' => 'Enable Flutterwave',
                'description' => 'Enable Flutterwave payment gateway.',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'flutterwave_public_key',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::INTEGRATIONS,
                'label' => 'Flutterwave Public Key',
                'description' => 'Public API key for Flutterwave.',
                'sort_order' => 2,
                'is_public' => false,
            ],
            [
                'key' => 'flutterwave_secret_key',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::INTEGRATIONS,
                'label' => 'Flutterwave Secret Key',
                'description' => 'Secret API key for Flutterwave.',
                'sort_order' => 3,
                'is_public' => false,
            ],
            [
                'key' => 'google_analytics_id',
                'value' => '',
                'type' => SettingType::STRING,
                'group' => SettingGroup::INTEGRATIONS,
                'label' => 'Google Analytics ID',
                'description' => 'Measurement ID for Google Analytics.',
                'sort_order' => 4,
                'is_public' => true,
            ],

            // System
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Maintenance Mode',
                'description' => 'Put the storefront into maintenance mode.',
                'sort_order' => 1,
                'is_public' => false,
            ],
            [
                'key' => 'debug_mode',
                'value' => '0',
                'type' => SettingType::BOOLEAN,
                'group' => SettingGroup::SYSTEM,
                'label' => 'Debug Mode',
                'description' => 'Enable detailed error output. Use only in development.',
                'sort_order' => 2,
                'is_public' => false,
            ],

            // Social (existing)
            ['key' => 'facebook', 'value' => 'https://facebook.com/vestra', 'type' => SettingType::STRING, 'group' => SettingGroup::SOCIAL, 'label' => 'Facebook', 'sort_order' => 1, 'is_public' => true],
            ['key' => 'instagram', 'value' => 'https://instagram.com/vestra', 'type' => SettingType::STRING, 'group' => SettingGroup::SOCIAL, 'label' => 'Instagram', 'sort_order' => 2, 'is_public' => true],
            ['key' => 'linkedin', 'value' => 'https://linkedin.com/company/vestra', 'type' => SettingType::STRING, 'group' => SettingGroup::SOCIAL, 'label' => 'LinkedIn', 'sort_order' => 3, 'is_public' => true],

            // Content (existing)
            ['key' => 'mission', 'value' => 'To deliver premium garment care solutions that protect your fabrics and the planet.', 'type' => SettingType::TEXT, 'group' => SettingGroup::CONTENT, 'label' => 'Mission', 'sort_order' => 1, 'is_public' => true],
            ['key' => 'vision', 'value' => 'To become the global standard for professional and sustainable fabric care.', 'type' => SettingType::TEXT, 'group' => SettingGroup::CONTENT, 'label' => 'Vision', 'sort_order' => 2, 'is_public' => true],
            ['key' => 'company_description', 'value' => 'VESTRA is a premium fabric care brand dedicated to developing high-performance cleaning solutions that combine advanced chemistry, innovation, and exceptional garment care.', 'type' => SettingType::TEXT, 'group' => SettingGroup::CONTENT, 'label' => 'Company Description', 'sort_order' => 3, 'is_public' => true],
            ['key' => 'philosophy', 'value' => 'We believe fabric care should do more than clean. It should preserve, protect, and prolong the life of every garment we touch.', 'type' => SettingType::TEXT, 'group' => SettingGroup::CONTENT, 'label' => 'Philosophy', 'sort_order' => 4, 'is_public' => true],
            ['key' => 'footer_text', 'value' => '© '.date('Y').' VESTRA. All rights reserved. Premium garment care solutions.', 'type' => SettingType::TEXT, 'group' => SettingGroup::CONTENT, 'label' => 'Footer Text', 'sort_order' => 5, 'is_public' => true],
            ['key' => 'founded', 'value' => '2020', 'type' => SettingType::STRING, 'group' => SettingGroup::GENERAL, 'label' => 'Founded Year', 'sort_order' => 13, 'is_public' => true],
            ['key' => 'headquarters', 'value' => 'Kampala, Uganda', 'type' => SettingType::STRING, 'group' => SettingGroup::GENERAL, 'label' => 'Headquarters', 'sort_order' => 14, 'is_public' => true],
            ['key' => 'core_values', 'value' => json_encode([
                ['icon' => 'FlaskConical', 'title' => 'Innovation', 'description' => 'We continuously research and develop better formulas for modern fabric care.'],
                ['icon' => 'ShieldCheck', 'title' => 'Quality', 'description' => 'Every product meets strict quality standards for professional results.'],
                ['icon' => 'Leaf', 'title' => 'Responsibility', 'description' => 'We create effective solutions while caring for people and the environment.'],
                ['icon' => 'Users', 'title' => 'Partnership', 'description' => 'We build lasting relationships with distributors, laundries, and customers.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Core Values', 'sort_order' => 6, 'is_public' => true],
            ['key' => 'distributor_benefits', 'value' => json_encode([
                ['icon' => 'Award', 'title' => 'Exclusive Territory', 'description' => 'Gain protected distribution rights in your region.'],
                ['icon' => 'Truck', 'title' => 'Reliable Supply', 'description' => 'Consistent product availability and timely deliveries.'],
                ['icon' => 'BadgeCheck', 'title' => 'Marketing Support', 'description' => 'Access branded materials and promotional resources.'],
                ['icon' => 'Sparkles', 'title' => 'Training', 'description' => 'Receive product knowledge and sales training from our team.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Distributor Benefits', 'sort_order' => 7, 'is_public' => true],
            ['key' => 'hero_features', 'value' => json_encode([
                ['icon' => 'Shield', 'title' => 'Professional', 'description' => 'Results'],
                ['icon' => 'Leaf', 'title' => 'Fabric', 'description' => 'Protection'],
                ['icon' => 'FlaskConical', 'title' => 'Innovative', 'description' => 'Formulations'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Hero Features', 'sort_order' => 8, 'is_public' => true],
            ['key' => 'promise_items', 'value' => json_encode([
                ['icon' => 'Award', 'title' => 'Outstanding Cleaning Performance', 'description' => 'Powerful cleaning that gets the job done.'],
                ['icon' => 'ShieldCheck', 'title' => 'Fabric Protection', 'description' => 'Gentle on fabrics, tough on dirt.'],
                ['icon' => 'BadgeCheck', 'title' => 'Consistent Quality', 'description' => 'Reliable performance in every bottle.'],
                ['icon' => 'Users', 'title' => 'Professional Results', 'description' => 'Designed for professional and everyday excellence.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Promise Items', 'sort_order' => 9, 'is_public' => true],
            ['key' => 'why_choose_features', 'value' => json_encode([
                ['icon' => 'Droplets', 'title' => 'Deep Cleaning', 'description' => 'Advanced formulas penetrate fibers for thorough cleaning.'],
                ['icon' => 'Shield', 'title' => 'Fabric Safe', 'description' => 'Protects colors and delicate fabrics during every wash.'],
                ['icon' => 'Leaf', 'title' => 'Eco Conscious', 'description' => 'Formulated with environmental responsibility in mind.'],
                ['icon' => 'Sparkles', 'title' => 'Long Lasting Freshness', 'description' => 'Keeps fabrics smelling fresh for longer.'],
                ['icon' => 'FlaskConical', 'title' => 'Scientifically Tested', 'description' => 'Proven performance through rigorous testing.'],
                ['icon' => 'Truck', 'title' => 'Professional Grade', 'description' => 'Trusted by professionals and commercial laundries.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Why Choose Features', 'sort_order' => 10, 'is_public' => true],
            ['key' => 'general_faqs', 'value' => json_encode([
                ['question' => 'Where can I buy VESTRA products?', 'answer' => 'VESTRA products are available through authorized distributors, select retail stores, and our online store once launched.'],
                ['question' => 'Are VESTRA products safe for all fabrics?', 'answer' => 'Each product is formulated for specific fabric types. Please check the product label or page for recommended usage.'],
                ['question' => 'Do you offer bulk or commercial pricing?', 'answer' => 'Yes. We offer competitive pricing for commercial laundries, hotels, and bulk buyers. Contact us for a quote.'],
                ['question' => 'How can I become a distributor?', 'answer' => 'Fill out the distributor application form on our Become a Distributor page and our team will get in touch.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'General FAQs', 'sort_order' => 11, 'is_public' => true],
            ['key' => 'distributor_faqs', 'value' => json_encode([
                ['question' => 'What is the minimum order quantity?', 'answer' => 'Minimum order quantities vary by product. Our team will share the full price list and MOQ after reviewing your application.'],
                ['question' => 'Do I need a registered business to apply?', 'answer' => 'Yes, we prefer working with registered businesses that have experience in distribution or retail.'],
                ['question' => 'How long does the approval process take?', 'answer' => 'Applications are typically reviewed within 5-7 business days.'],
                ['question' => 'What support do distributors receive?', 'answer' => 'Distributors receive marketing materials, training, territory protection, and dedicated account support.'],
            ]), 'type' => SettingType::JSON, 'group' => SettingGroup::CONTENT, 'label' => 'Distributor FAQs', 'sort_order' => 12, 'is_public' => true],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(['key' => $setting['key']], $setting);
        }
    }
}
